# Generated by Django 3.2.5 on 2021-07-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamtodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtodo',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
