# Generated by Django 3.2.4 on 2021-06-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_alter_videocall_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocall',
            old_name='token',
            new_name='s_id',
        ),
    ]
