# Generated by Django 3.2.5 on 2021-07-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_teammailbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammailbox',
            old_name='messsage',
            new_name='message',
        ),
    ]
