# Generated by Django 3.2.4 on 2021-07-01 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
